### ISSUE TITLE
How to create sample data (audio) from wav or MP3 file

### ISSUE THREAD

**Issue by dhanajik** [swharden/FftSharp#30]
Hi,

How can create sample data from wave/mp2 file? I need to pass the audio file path or convert the audio file to the audio sample data (FftSharp.SampleData.SampleAudio1()).

Please guide me or provide some samples where I can convert the audio file to the required sample data array.

Thank you in adabance 

Dhan

**Comment by swharden** [comment]
Hi @dhanajik, this code sample shows you how to read data from a WAV file
https://github.com/swharden/Spectrogram#read-data-from-a-wav-file
