### ISSUE TITLE
Filter Creation Off-By-1

### ISSUE THREAD

**Issue by frouwen** [swharden/FftSharp#46]
https://github.com/swharden/FftSharp/blob/a736f9091bfadf30e4d5d35e67db51a0594369f2/src/FftSharp/Windows/Hanning.cs#L18

Shouldn't this line be:
window[i] = 0.5 - 0.5 * Math.Cos(2 * Math.PI * i / (size-1));

Otherwise the window is not symmetric.

**Comment by swharden** [comment]
Thanks for reporting this @frouwen! In #47 I extensively tested all the window functions against Python/scipy to ensure correctness, making a few small corrections in the process. I'm releasing an updated NuGet package tonight reflecting these changes 👍 🚀

**Comment by frouwen** [comment]
Awesome! You made some very nice improvements! Your libraries make my life considerably easier. Keep up the good work 😄.
