### ISSUE TITLE
Input length must be an even power of 2

### ISSUE THREAD

**Issue by HamidLaktarash** [swharden/FftSharp#48]
I have real audio signal wave in form of double[]. it's length isn't power of 2. what should I do?

**Comment by swharden** [comment]
Hi @HamidLaktarash,

There's a helper function that can pad an array with zeros and always return one that is an even power of 2

```cs
double[] padded = FftSharp.Pad.ZeroPad(input);
```

**Comment by swharden** [comment]
... it's pretty simple, so you could also implement this yourself and not rely on the helper function if you don't want to

https://github.com/swharden/FftSharp/blob/e2d70581086aae8044d0be5c628ab9a7506fa827/src/FftSharp/Pad.cs#L35-L54
