### ISSUE TITLE
update to be dependent on Net 6.0

### ISSUE THREAD

**Issue by btayakin** [swharden/FftSharp#52]
You library is very helpful! Thank you so much! Do you guys plan to update the Target Framework to be Net 6.0 instead of Net 5.0 ?

**Comment by swharden** [comment]
Hi @btayakin, I'm glad you enjoy it!

The library has several targets including .NET 5, but you can use it in .NET 6 applications.

If I add .NET6-specfic code I'll update the targets, but even without this you can use it as it is in .NET 6, .NET 7, .NET 8, etc. without this package having to be recompiled and redeployed for those versions.

I hope that explanation makes sense! 🚀
