### ISSUE TITLE
FFTphase function

### ISSUE THREAD

**Issue by aquilesr** [swharden/FftSharp#58]
This would be a very useful function to be able to recreate the shape of a wave

**Comment by swharden** [comment]
Hi @aquilesr, can you clarify the feature request? Linking to another library that does something similar, or a web page demonstrating this type of analysis would be very helpful.

Thanks!

**Comment by swharden** [comment]
Note that you can create your own array of complex numbers, apply the FFT, then read the result. My understanding is that the imaginary component of the resulting data represents phase.

https://github.com/swharden/FftSharp#fft-using-complex-numbers

**Comment by aquilesr** [comment]
Hi Scott,
Sorry for my bad English, it's not my native language.
Waves have 3 characteristics, magnitude, frequency and phase.
You did the FFTmagnitude and FFTfreq function. However I think you are missing FFTphase, which I don't think is the imaginary component, but the FFT=a+bi => phase=tag-1(b/a) and some other considerations.

I congratulate you for your great work which has been very useful to me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by swharden** [comment]
Thank you for clarifying! I better understand the request now, and I agree this would be a great feature to add.

![image](https://user-images.githubusercontent.com/4165489/218554460-cf564743-34b3-4592-a20b-5ccce68007e9.png)

* https://www.gaussianwaves.com/2015/11/interpreting-fft-results-obtaining-magnitude-and-phase-information/ 
* https://courses.engr.illinois.edu/cs445/fa2020/lectures/Lecture%2003%20-%20Thinking%20in%20Frequency%20-%20Online.pdf

**Comment by swharden** [comment]
Took a while to get to it, but I'm adding this feature in now.

Note that one can measure phase like this:

```cs
double[] values = /* your data */
Complex[] fft = FftSharp.Transform.FFT(values);
double[] phases = fft.Select(x=>Math.Atan2(x.Imaginary, x.Real)).ToArray();
```
