### ISSUE TITLE
Is there an equivalent to numpy fft.irfft?

### ISSUE THREAD

**Issue by FrankHileman** [swharden/FftSharp#71]
Thank you to produce this library. Does it contain an equivalent to numpy fft.irfft? I did find the complex inverse.
https://numpy.org/doc/stable/reference/generated/numpy.fft.irfft.html

I am a C# programmer, so I understand how to convert from in-place to generating a new array.

**Comment by swharden** [comment]
Hi @FrankHileman, thank you for this question!

Presently no, FftSharp does not have an `irfft` function. I'd be happy to add one in though! 

I would probably name it `InverseReal()` It could live alongside the `ForwardReal()` function:

https://github.com/swharden/FftSharp/blob/6f341bb1f33a7c99ad09470a9d81caf0a2471126/src/FftSharp/FFT.cs#L64-L74

If you wish to add this and create a pull request, I would be happy to merge it in and publish a new package with this feature

**Comment by FrankHileman** [comment]
Hello @swharden, Thank you for the reply. I am still reading about how to convert an inverse complex method into an inverse real method, so I am not in a position to implement it immediately.

**Comment by gsgou** [comment]
I will have a look if it can be based in this implementation:
https://github.com/hughpyle/inguz-DSPUtil/blob/master/Fourier.cs#L198

**Comment by gsgou** [comment]
Maybe could be based on this implementation:
https://innovatiestudio.hku.nl/?p=1213
