### ISSUE TITLE
FftOperations.RFFT_WithoutChecks doesn't use input

### ISSUE THREAD

**Issue by FrankHileman** [swharden/FftSharp#73]
`RFFT_WithoutChecks(Span<System.Numerics.Complex> destination, Span<System.Numerics.Complex> input)` only uses the length of the input parameter, and not the data inside. The ForwardReal method calling this method apparently isn't tested. 

I am curious about the ForwardReal methods. Are they supposed to be identical in output to the corresponding numpy methods? I ask because the  the numpy.fft.rfft method states "If the input a contains an imaginary part, it is silently discarded." Secondly, the purpose of rfft seems to be increased efficiency, because it uses a different algorithm to avoid calculating the portion thrown out.

**Comment by swharden** [comment]
Hi @FrankHileman, thanks for raising this issue!

Let's take a closer look at the code under discussion:

https://github.com/swharden/FftSharp/blob/6f4c322781a792a770a01c67f562911d9e5761eb/src/FftSharp/FftOperations.cs#L86-L101

> The ForwardReal method calling this method apparently isn't tested.

Thanks for pointing that out! I'll start by adding this test now, then follow-up.
