### ISSUE TITLE
FFT: Support arbitrary sized vectors using Bluestein's algorithm

### ISSUE THREAD

**Issue by gsgou** [swharden/FftSharp#77]
could be based on mathnet-numerics implementation:
https://github.com/mathnet/mathnet-numerics/blob/master/src/Numerics/Providers/FourierTransform/ManagedFourierTransformProvider.Bluestein.cs#L252

**Comment by swharden** [comment]
Hi @gsgou, 

There are some other (non-FFT) transforms in FftSharp.Experimental. If you're interested in adding `BluesteinForward()` and `BluesteinInverse()` in there, you're welcome to submit a PR!

This is slow, but it's worth noting it works for arbitrary length datasets:

```cs
double[] prime = { 1, 2, 3, 4, 5, 6, 7 };
System.Numerics.Complex[] primeComplex = prime.Select(x => new System.Numerics.Complex(x, 0)).ToArray();
System.Numerics.Complex[] result = FftSharp.Experimental.DFT(primeComplex);
```

I don't intend to add Bluesteins to this library myself soon so I'll close this issue for now, but if you or someone else is interested in getting development started I'm happy to open it back up again! Thanks for this suggestion

**Comment by swharden** [comment]
... okay this may be pretty easy actually. I found this, and this could be as easy as copy/pasting it in. It looks to be under a MIT license:

https://www.nayuki.io/res/free-small-fft-in-multiple-languages/Fft.cs

```cs
/* 
* Computes the discrete Fourier transform (DFT) of the given complex vector, storing the result back into the vector.
* The vector can have any length. This requires the convolution function, which in turn requires the radix-2 FFT function.
* Uses Bluestein's chirp z-transform algorithm.
*/
public static void TransformBluestein(Complex[] vec, bool inverse) {
// Find a power-of-2 convolution length m such that m >= n * 2 + 1
int n = vec.Length;
if (n >= 0x20000000)
	throw new ArgumentException("Array too large");
int m = 1;
while (m < n * 2 + 1)
	m *= 2;

// Trigonometric table
Complex[] expTable = new Complex[n];
double coef = Math.PI / n * (inverse ? 1 : -1);
for (int i = 0; i < n; i++) {
	int j = (int)((long)i * i % (n * 2));  // This is more accurate than j = i * i
	expTable[i] = Complex.Exp(new Complex(0, j * coef));
}

// Temporary vectors and preprocessing
Complex[] avec = new Complex[m];
for (int i = 0; i < n; i++)
	avec[i] = vec[i] * expTable[i];
Complex[] bvec = new Complex[m];
bvec[0] = expTable[0];
for (int i = 1; i < n; i++)
	bvec[i] = bvec[m - i] = Complex.Conjugate(expTable[i]);

// Convolution
Complex[] cvec = new Complex[m];
Convolve(avec, bvec, cvec);

// Postprocessing
for (int i = 0; i < n; i++)
	vec[i] = cvec[i] * expTable[i];
}
```

**Comment by swharden** [comment]
This needs more work so I'm leaving it in the `Experimental` namespace so I can publish the package right now, but we can test this a little more thoroughly and add it into the main API soon. I'm merging #80 in so we both have access to the code if/when one of us decides to pick it up!

```cs
// this will work when I publish the new package in a few minutes
double[] prime = { 1, 2, 3, 4, 5, 6, 7 };
System.Numerics.Complex[] result = FftSharp.Experimental.Bluestein(prime);
```

**Comment by gsgou** [comment]
tks a lot @swharden, we can catch up on this at a later time.

**Comment by swharden** [comment]
It's been a while since this was discussed, but today I'm moving this code to:

```cs
FftSharp.Bluestein.Forward();
FftSharp.Bluestein.Inverse();
```
