### ISSUE TITLE
Please make an example IFFT 

### ISSUE THREAD

**Issue by smkang123** [swharden/FftSharp#84]
I'm going to use IFFT "Spectrum length must be a power of two plus one"
Please make an example

**Comment by swharden** [comment]
> Spectrum length must be a power of two plus one

Hi @smkang123, I'm not sure I understand this part of the question. However, here is an example of how IFFT may be used:

```cs
Complex[] data = /* your code here */

// forward FFT
FftSharp.FFT.Forward(data); 

// inverse FFT (IFFT)
FftSharp.FFT.Inverse(data); 
```
