### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by BrandMChaos** [swharden/FftSharp#85]
I'm not sure where I need to go and what to implement in this repository. I see the QuickStart section, but just further confused me

**Comment by swharden** [comment]
Hi @BrandMChaos, 

I assume this has been resolved by now, but if not you can download the repository, double-click the solution file in the `src` folder, and run the Demo project 👍 

https://github.com/swharden/FftSharp/archive/refs/heads/main.zip
